### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by HaydenHu** [OneKiwiTech/kicad-fanout-tool#1]
![image](https://user-images.githubusercontent.com/30103277/183892159-2c2fdb46-7a11-4bf6-8c9f-d4bdaafaba66.png)

kicad6.0.6
win10

**Comment by devytime** [comment]
Same here. Also on Win 10 Kicad 6.07. A possible fix is to convert the one yaml file to json (json parser comes standard with python). This avoids needing the additional module in Kicad python.

**Comment by thanhduongvs** [comment]
hi @HaydenHu  ,
Thanks for report. Please update to version 2022.08.1
![Untitled](https://user-images.githubusercontent.com/8404232/184467159-440e2fc0-3856-4dff-b7cc-a7caa1ed2d1d.png)
3
