### ISSUE TITLE
SVG format not recognized

### ISSUE THREAD

**Issue by devytime** [OneKiwiTech/kicad-fanout-tool#2]
The image files with .svg format can't be opened by Kicad, unrecognized format. The files themselves open fine in svg viewer or Inkscape for example. On Win10 with Kicad 6.07.

**Comment by thanhduongvs** [comment]
hi @devytime ,
Thanks for report. Please update to version 2022.08.13
![Untitled](https://user-images.githubusercontent.com/8404232/184467123-c26aa015-a8e6-4f3c-957d-e3fd1a1c886b.png)
